### ISSUE TITLE
Switches on left sidebar don't toggle unless user clicks on rule for details

### ISSUE THREAD

**Issue by darahak** [SilencerWeb/eslint-config-website#8]
Hi,

First of all, thank you for publishing this tool. This is something that was really missing from the ESLint ecosystem :+1: 

There seems to be an issue with the switches: they update on the right panel, but don't on the left sidebar. They only update when I select a rule to display rule details.

[![](https://j.gifs.com/voXyjL.gif)]()

**Comment by SilencerWeb** [comment]
@darahak, thanks so much, fixed :)
